baseurl = "/"
title = "CarpiCUN"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "es-mx"
languageLang = "es"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"

# Enable comments by entering your Disqus shortname
#disqusShortname = "devcows"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Inicio"
    url  = "/"
    weight = 1

#[[menu.main]]
#    name = "Blog"
#    url  = "/blog/"
#    weight = 2

#[[menu.main]]
#    name = "FAQ"
#    identifier = "faq"
#    url  = "/faq/"
#    weight = 3

[[menu.main]]
    name = "Contacto"
    url  = "/contacto/"
    weight = 4

# Top bar social links menu

 #[[menu.topbar]]
 #   weight = 1
 #   name = "GitHub"
 #   url = "https://github.com/devcows/hugo-universal-theme"
 #   pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:contacto@carpicun.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]

	# Enable Google Tag Manager
	googleTagManager = "GTM-5SCV28X"
	
    viewMorePostLink = "/blog/"
    author = "CarpiCUN"
    defaultKeywords = ["carpicun", "carpinteria", "cancun", "cun", "carpintero"]
    defaultDescription = "Carpintería CUN - CarpiCUN"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "carpicun"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contacto@carpicun.com"

    about_us = "<p>Carpintería de calidad en Cancún</p>"
    copyright = "Copyright (c) 2018, CarpiCUN; todos los derechos reservados."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>CarpiCUN SA de CV</strong>
        <br>Calle Fuego
        <br>Cancún, Quintana Roo
        <br>(77500)
        <br><strong>Mexico</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
#    blog = "/blog/:year/:month/:day/:filename/"
    blog = "/portfolio/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contáctanos al +52 1 (998) 865-6119 o al email contacto@carpicun.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimoniales"
    subtitle = "Ayudamos a muchos clientes con trabajos de carpintería en Cancún, Playa del Carmen, Tulúm, Mérida, Ciudad de México, Monterrey, Guadalajara y varias otras ciudades. Nos da orgullo haberlo hecho con calidad y a tiempo para dejarlos satisfechos. Aquí las historias de algunos clientes de CarpiCUN:"

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "¿Quieres saber como CarpiCUN puede ayudarte?"
    subtitle = "CarpiCUN tiene como objetivo trabajar seriamente, entregar a tiempo y con excelente calidad en carpintería en Cancún."
    link_url = "/contacto"
    link_text = "Pide una cotización"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Nuestros Clientes"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
